src/components/ComponentEditor/components/PrometheusExporterGithub.tsx
src/components/ComponentList/index.tsx
src/lib/river.ts

feat: add github exporter

---

src/components/ComponentList/index.tsx

also cleans up copy & paste for list entries

feat: add search box to component list

---

src/components/ComponentEditor/inputs/MultiBlock.tsx
src/lib/river.ts

need to add some kind of componentspec for this to be usable as there is currently now way to know if a block is repeatable or not

feat: add multi-block input

---

src/components/ComponentEditor/components/PrometheusRemoteWrite.tsx
src/components/ComponentEditor/components/PrometheusScrape.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentEditor/inputs/MultiBlock.tsx
src/lib/components.ts
src/lib/river.test.ts
src/lib/river.ts

allows us to differentiate between a single block and a list of blocks with only one element

feat: add spec to conversion functions

---

src/components/ComponentEditor/components/DiscoveryEc2.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentEditor/inputs/ReferenceSelect.tsx
src/components/ComponentList/index.tsx

feat: add new component `discovery.ec2`

---

src/components/ComponentEditor/components/PrometheusExporterRedis.tsx

needed as react-hook-form does not play nice with conditional sections

fix: remove collapsablesection with a simple header

---

src/components/ComponentEditor/common/TlsBlock.tsx
src/components/ComponentEditor/components/OTelColExporterPrometheus.tsx
src/components/ComponentEditor/components/OTelColProcessorBatch.tsx
src/components/ComponentEditor/components/OTelColReceiverOTLP.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentEditor/inputs/ReferenceMultiSelect.tsx
src/components/ComponentEditor/inputs/ReferenceSelect.tsx
src/components/ComponentList/index.tsx
src/index.css
src/lib/components.ts
src/lib/river.test.ts
src/lib/river.ts

This also builds a better foundation for more involved component forms
closes: #92
closes: #85
closes: #83

feat: add otel components

---

src/components/ComponentEditor/components/PrometheusExporterRedis.tsx
src/lib/components.ts

feat: complete implementation of prometheus.exporter.redis

---

src/components/ComponentEditor/components/PrometheusExporterUnix.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentEditor/inputs/ReferenceSelect.tsx
src/components/ExamplesCatalog/examples.tsx
src/lib/components.ts

covers most usecases but still not fully implemented

feat: surface level implementation of the unix exporter

---

src/components/ComponentEditor/components/DiscoveryFile.tsx
src/components/ComponentEditor/components/LokiSourceFile.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentList/index.tsx
src/lib/components.ts

feat: add loki file source and discovery

---

src/components/ComponentEditor/components/PrometheusRelabel.tsx
src/components/ComponentEditor/index.tsx
src/components/ExamplesCatalog/examples.tsx
src/lib/components.ts

also improves the linux example
closes #115

feat: add promethes relabel

---

src/components/ComponentEditor/components/DiscoveryKubernetes.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentList/index.tsx
src/lib/components.ts

feat: add discovery.kubernetes component

---

src/components/ConfigEditor/index.tsx

this removes the need to press enter after loading the model from localstorage or url

fix: update components after parser is initialized

---

src/App.tsx

looks better on most common viewport sizes

style: use 50% min-width for modal

---

src/components/ComponentEditor/common/AuthenticationEditor.tsx
src/components/ComponentEditor/common/TlsConfig.tsx
src/components/ComponentEditor/components/PrometheusScrape.tsx
src/lib/components.ts

feat: complete prometheus.scrape

---

src/components/ComponentEditor/common/AuthenticationEditor.tsx
src/components/ComponentEditor/components/PrometheusRemoteWrite.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentEditor/inputs/MultiBlock.tsx
src/components/ComponentEditor/inputs/TypedInput.tsx
src/lib/components.ts
src/lib/river.test.ts
src/lib/river.ts

feat: finish prometheus remote write

---

src/components/ComponentEditor/common/TlsConfig.tsx
src/components/ComponentEditor/components/LokiWrite.tsx
src/components/ComponentEditor/components/PrometheusRemoteWrite.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentList/index.tsx
src/lib/components.ts

also fixes an issue with the TLSConfig in prometheus.remote_write
closes #68

feat: add loki.write component

---

src/components/ComponentEditor/components/LokiSourceWindowsEvent.tsx
src/components/ComponentEditor/index.tsx
src/components/ComponentEditor/inputs/TypedInput.tsx
src/components/ComponentList/index.tsx
src/components/ConfigurationWizard/sources/WindowsNode.ts
src/components/ConfigurationWizard/sources/index.ts
src/lib/components.ts

feat: add loki.source.windowsevent

---

package.json
src/components/ConfigEditor/index.tsx
src/lib/componentaddons.ts
src/lib/components.ts

feat: add way to set component specific markers

---

src/lib/components.ts
src/lib/river.test.ts

See https://raintank-corp.slack.com/archives/C03NCLB4GG7/p1698431277146729 for more context
cc @korniltsev

pyroscope: memory path fix
